---

- name: Clone Podman (conmon) Repo
  git:
    repo: https://github.com/containers/libpod/
    version: v1.5.1
    dest: "{{ podman.buildDir }}/src/github.com/containers/libpod"
    update: no
  become: yes
  become_user: "{{ ansible_user }}"
  environment:
        GOPATH: "{{ podman.buildDir }}/"
        GOOS: linux
        GOARCH: arm

- name: Compile Podman
  make:
    chdir: "{{ podman.buildDir }}/src/github.com/containers/libpod"
  register: podman_podman_buildok
  become: yes
  become_user: "{{ ansible_user }}"



- name: Install Podman [or so it says]
  make:
    target: install
    chdir: "{{ podman.buildDir }}/src/github.com/containers/libpod"
  when: podman_podman_buildok
