---

- name: Install requisite packages (likely present)
  apt:
    name:
      - podman 
      - fuse-overlayfs
    state: present
    force_apt_get: yes
    cache_valid_time: 84600
  register: podman_packages_present