---

- name: Install Connection Monitor (conmon)
  git:
    repo: https://github.com/containers/conmon.git
    version: v2.0.21
    dest: "{{ podman.buildDir }}/conmon/"
  become: yes
  become_user: "{{ ansible_user }}"



- name: Compile Connection Monitor (Part 1)
  make:
    chdir: "{{ podman.buildDir }}/conmon"
  register: podman_conmon_build_ok
  environment:
        GOPATH: "{{ podman.buildDir }}/"
        GOOS: linux
        GOARCH: arm

- name: Copy Compiled Binaries
  copy:
    src: "{{ podman.buildDir }}/conmon/bin/conmon"
    dest: /usr/local/bin
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  when: not podman_conmon_build_ok.failed

- name:  Check if CNI bindir "/usr/libexec/podman" exists
  stat:
    path: "/usr/local/libexec/podman"
  register: podman_libexec_cni

- name: create "/usr/libexec/podman" top-Level
  file:
    path: "/usr/local/libexec/podman"
    state: directory
    owner: root
    group: root
    mode: 0755
  when:
    not podman_libexec_cni.stat.exists

- name: Copy Compiled Binaries (Part 2)
  copy:
    src: "{{ podman.buildDir }}/conmon/bin/conmon"
    dest: /usr/local/libexec/podman/conmon
    owner: root
    group: root
    mode: 0755
    remote_src: yes
  when: not podman_conmon_build_ok.failed
